name: 'Radicati Layout Builder'
description: 'Sets up a basic layout builder config with a Landing Page content type'
type: 'Admin'
recipes:
  - radicati-recipe-media
install:
  - link
  - path
  - field
  - field_ui
  - pathauto
  - paragraphs
  - manage_display
  - layout_builder
  - layout_builder_browser
  - block_content_template
  - entity_browser
  - entity_reference_display
  - inline_block_title_automatic
  - inline_entity_form
  - layout_builder_operation_link
  - layout_builder_restrictions
  - slick
  - slick_entityreference
  - slick_ui
  - taxonomy
  - radicati_base
  - text_field_formatter
  - viewsreference
  - webform
  - fontawesome
  - fontawesome_menu_icons
  - radicati_components
  - radicati_layouts
config:
  import:
    link: "*"
    path: "*"
    pathauto: "*"
    manage_display: "*"
    paragraphs: "*"
    layout_builder: "*"
    block_content_template: "*"
    entity_browser: "*"
    inline_block_title_automatic: "*"
    entity_reference_display: "*"
    inline_entity_form: "*"
    layout_builder_browser: "*"
    layout_builder_operation_link: "*"
    layout_builder_restrictions: "*"
    text_field_formatter: "*"
    slick: "*"
    slick_entityreference: "*"
    slick_ui: "*"
    taxonomy: "*"
    radicati_base: "*"
    viewsreference: "*"
    webform: "*"
    fontawesome: "*"
    fontawesome_menu_icons: "*"
  actions:
    fontawesome.settings:
      simple_config_update:
        external_svg_location: 'https://kit.fontawesome.com/2b3c7d97da.js'
        allow_pseudo_elements: true